#!/usr/bin/bash

# # # # #
# Main  #
# # # # #

preX::main ()
{
    [[ "$(tty)" == "/dev/tty6" ]] && return
    [[ "$TERM" == "tmux-256color" ]] && return
    preX::mountPlexMedia
    type -P surfshark-vpn && preX::initVPN
    preX::cleanup
    preX::initGUI
}

# # # # # # # # # # # # # #
# FUNCTION IMPLEMENTATION #
# # # # # # # # # # # # # #

preX::initGUI ()
{
    unset -f preX::initGUI
    if [[ "$(tty)" == "/dev/tty1" ]]; then
        exec startx ~/.xinitrc dwm
    elif [[ "$(tty)" == "/dev/tty2" ]]; then
        exec startx ~/.xinitrc vswm
    else
        echo "Choose a Window Manager:"
        read sel
        exec startx ~/.xinitrc $sel
    fi
}

preX::initVPN ()
{
    OldIP="$(curl ip.me 2>/dev/null)"

    pgrep openvpn &>/dev/null &&                        \
        preX::printpretty 0 "VPN CONNECTED"                   \
            "VPN IP Address: $OldIP" &&                 \
        return ||                                       \
        yes | doas surfshark-vpn attack &>/dev/null &&  \
        NewIP="$(curl ip.me 2>/dev/null)" &&            \
        preX::printpretty 0 "VPN CONNECTED"                   \
            "Old IP Address: $OldIP"                    \
            "VPN IP Address: $NewIP" &&                 \
        return ||                                       \
        preX::printpretty 2 "VPN RETRYING" &&                 \
        doas surfshark-vpn down &>/dev/null &&          \
        yes | doas surfshark-vpn attack &>/dev/null &&  \
        NewIP="$(curl ip.me 2>/dev/null)" &&            \
        preX::printpretty 0 "VPN CONNECTED"                   \
            "Old IP Address: $OldIP"                    \
            "VPN IP Address: $NewIP" ||                 \
        preX::printpretty 1 "VPN NOT CONNECTED" "IP Address: $OldIP"
}

preX::mountPlexMedia ()
{
    [[ -e "$HOME/PlexMedia/Movies" ]] &&                    \
        preX::printpretty 0 "PLEXMEDIA MOUNTED" &&                \
        return ||                                           \
        sshfs cs@192.168.1.110:Media/ $HOME/PlexMedia/ &&   \
        preX::printpretty 0 "PLEXMEDIA MOUNTED" ||                \
        preX::printpretty 1 "PLEXMEDIA NOT MOUNTED"
}

preX::printpretty ()
{
    [[ -z "$2" ]] && exit 1

    case $1 in
        0)
            printf "\n\e[1m [\e[32m  %s  \e[0m\e[1m] \e[0m\n\n" "$2"
            [[ -z "$3" ]] || printf "\e[33;1m  INFO:\n\e[0m"
            for i in "$@"; do
                [[ "$i" == "$1" || "$i" == "$2" ]] || printf "  - %s\n" "$i"
            done
            [[ -z "$3" ]] || printf "\n"
            ;;
        1)
            printf "\n\e[1m [\e[31m  %s  \e[0m\e[1m] \e[0m\n\n" "$2"
            ;;
        2)
            printf "\n\e[1m [\e[33m  %s  \e[0m\e[1m] \e[0m\n\n" "$2"
            ;;
        *)
            exit ;;
    esac
}

preX::cleanup ()
{
    # Variables
    unset i
    unset NewIP
    unset OldIP
    # Functions
    unset -f preX::mountPlexMedia
    unset -f preX::initVPN
    unset -f preX::printpretty
    unset -f preX::main
    unset -f preX::cleanup
}

preX::main
