#!/bin/bash

Selection=$(echo -e "Qutebrowser\nTor Browser" | dmenu -i -p Browser:)

case "$Selection" in
    Qutebrowser)
        Options=$(echo | dmenu -i -p "Type?");
        case "$Options" in
            p | P)
                qutebrowser --target private-window;
                exit ;;
            w | W)
                qutebrowser --target window;
                exit ;;
            *)
                qutebrowser;
                exit ;;
        esac
        exit ;;
    "Tor Browser")
        Check=$(echo -e "Yes\nNo" | dmenu -i -n 1 -p "Are you sure?");
        case "$Check" in
            Yes)    torbrowser-launcher; exit ;;
            No)     exit ;;
        esac; exit ;;
    *)  exit ;;
esac
