#!/bin/bash

if [ -e /sys/class/power_supply/BAT0/capacity ]; then
    while true; do
        printf -v barformat ' %(%y%m%d %H%M%S)T %03d ' -1 "$(< /sys/class/power_supply/BAT0/capacity)"
        xsetroot -name "$barformat"
        sleep 1s
    done
else
    while true; do
        printf -v barformat ' %(%y%m%d %H%M%S)T ' -1
        sleep 1s
    done
fi
