#!/bin/bash
if [ -e /sys/class/power_supply/BAT0/capacity ]; then
    while true; do
        bat="$(cat /sys/class/power_supply/BAT0/capacity)"
        [[ "$bat" -ge 100 ]] && showbat="$bat" ||       \
            [[ "$bat" -lt 10 ]] && showbat="00$bat" ||  \
            [[ "$bat" -lt 100 ]] && showbat="0$bat"

        xsetroot -name " $(/bin/date "+%y%m%d %H%M%S") $showbat "
        sleep 1s
    done &
else
    while true; do
        xsetroot -name " $(/bin/date "+%y%m%d %H%M%S") "
        sleep 1s
    done &
fi
