#!/bin/bash

main()
{
    if [ "$1" == "-d" ]; then
        gitcmd="git --git-dir=$HOME/dotfiles --work-tree=$HOME"
        gitarg="$2"
        shift 2
    else
        gitcmd="git"
        gitarg="$1"
        shift
    fi

    case "$gitarg" in
        ps)
            $gitcmd push "$@"
            ;;
        pl)
            $gitcmd pull "$@"
            ;;
        'st'|'')
            $gitcmd status "$@"
            ;;
        cm)
            $gitcmd commit "$@"
            ;;
        a)
            $gitcmd add "$@"
            ;;
        co)
            $gitcmd checkout "$@"
            ;;
        *)
            $gitcmd "$gitarg" "$@"
            ;;
    esac
}

main "$@"
