#!/bin/bash

Selection=$(echo -e "Shutdown\nRestart" | dmenu -i -p "Power off:")
case "$Selection" in
    Shutdown)   [ "$(echo -e "Yes\nNo" | dmenu -i -n 1 -nf red -sb red -sf black -p "[S] Are you sure?")" == "Yes" ] && doas surfshark-vpn down && shutdown now || exit;
                exit ;;
    Restart)    [ "$(echo -e "Yes\nNo" | dmenu -i -n 1 -p "[R] Are you sure?")" == "Yes" ] && reboot || exit;
                exit ;;
esac
