#!/bin/bash

tmux-default::main ()
{
    local SESSION="default"

    if tmux attach-session -t $SESSION 2>/dev/null; then
        exit 0
    else
        tmux-default::createSession
        tmux attach-session -t $SESSION
    fi
}

tmux-default::createSession ()
{
    tmux new -s $SESSION -d
    tmux rename-window -t $SESSION sys-mon
    tmux send-keys -t $SESSION 'htop' Enter
    tmux split-window -v -t $SESSION
    tmux send-keys -t $SESSION \
        'clear; tput civis; while true; do sensors | grep "Pack\|Core\|Exha"; tput cup 0 0; sleep 2; done' \
        Enter
    tmux resize-pane -t $SESSION -y 5
    tmux select-pane -U
    tmux new-window -t $SESSION
}

tmux-default::main
