#!/bin/bash

tmux-scratchpad::main ()
{
    local SESSION="scratchpad"

    if tmux attach-session -t $SESSION 2>/dev/null; then
        exit 0
    else
        tmux-scratchpad::createSession
        tmux-scratchpad::attachSession "$@"
    fi
}

tmux-scratchpad::createSession ()
{
    tmux new -s $SESSION -d
    tmux rename-window -t $SESSION shell
    tmux new-window -t $SESSION
    tmux rename-window -t $SESSION sys-mon
    tmux send-keys -t $SESSION 'htop' Enter
    tmux send-keys -t $SESSION
    tmux split-window -v -t $SESSION
    tmux send-keys -t $SESSION \
        'clear; tput civis; while true; do sensors | grep "Pack\|Core\|Exha"; tput cup 0 0; sleep 2; done' \
        Enter
    tmux resize-pane -t $SESSION -y 1
    tmux select-pane -U
}

tmux-scratchpad::attachSession ()
{
    [ -z $1 ] && \
        tmux select-window -t $SESSION:0.0 || \
        tmux select-window -t $SESSION:0."$1"
    tmux attach -t $SESSION
}

tmux-scratchpad::main "$@"
